# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8aca59e1a141205fd1e5cddb9e08b66590641f4ac65eb12e8ea176285738dbd0684016d4153c620cdbc60e663b08062dfacdb04441da6a01c2bf0c4acf1b7a0

test:
  secret_key_base: b00ae02abfba9e76193208b0500f29c672d8e72d1985fb6d6969c2858961b4b3b6280f44467fa7a45c4f0ba1c3a5b75de84e739108d2fcce95fe00c2a9da4be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
